### ISSUE TITLE
Downgrade node engine to 8.12.0

### ISSUE THREAD

**Issue by marctorrelles** [pocka/vue-docgen-loader#13]
**Is your feature request related to a problem? Please describe.**

At the company I work we would like to use the [storybook docs addon](https://github.com/storybookjs/storybook/tree/master/addons/docs), which has this library as a dependency and (in our case) involves an unnecessary friction. Right now we are running `8.12.0`, but this package [requires](https://github.com/storybookjs/storybook/blob/next/addons/docs/package.json#L79) `8.16.0` and upgrading to it has side-effects that we would like to avoid.

**Describe the solution you'd like**

It would be possible to downgrade (or even remove) the engine used? Is there any limitation to use the `8.16` minimum version?

**Describe alternatives you've considered**

This 👆🏻

**Comment by pocka** [comment]
The primary reason for the `engine >= 8.16`<sup>[0]</sup> was to generate a more simple and modern code ([the loader's source code is compiled by `@babel/preset-env`](https://github.com/pocka/vue-docgen-loader/blob/master/package.json#L75)) and to avoid mysterious errors due to old engines. So I think there is no limitation to use `8.x`. But I think it should not support older versions because node.js 8.x reached End-of-Life on 31st December 2019.

You can skip engine check by adding `--ignore-engines` option (Yarn) or setting `engine-strict` to `false` (npm).

[0] ... at the time of writing the first version of this addon, the latest LTS release was `8.16`.
